blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/aktionariat/reports/issues/new/choose ://github.com/WalletConnect/walletconnect-monorepo/discussions/new?category=swift-ios
    about: Ask questions and discuss with other community members.
  - name: View our FAQ
    url: https://www.aktionariat.com/faq/en
    about: See our frequently asked questions
