blank_issues_enabled: false
contact_links:
  - name: Visit our FAQ
    url: https://www.aktionariat.com/faq/en
    about: See our frequently asked questions
  - name: Visit our Documentation Page
    url: https://www.aktionariat.com/documentation
    about: See our documentation page